Update to add java 8 compat, latest mockito, etc...
AzureAD/microsoft-authentication-library-for-android pull request #1244
Opened 2020-12-07 19:54 UTC by shoatman

Upgrade mockito android version to latest
Updated compile sdk version
Updated target sdk version
Added java 8 compat (https://developer.android.com/studio/write/java8-support)

2020-12-07 20:57 UTC, AdamBJohnsonx commented on gradle.properties
> +abiSelection=x86_64
```suggestion
abiSelection=x86_64

```

2020-12-07 20:57 UTC, AdamBJohnsonx commented on msal/build.gradle
>      buildToolsVersion rootProject.ext.buildToolsVersion
```suggestion
```

2020-12-07 20:58 UTC, AdamBJohnsonx approved these changes

2021-01-04 18:45 UTC, iambmelt requested changes
Since Travis CI is no longer going to be used, suggest we update the README to remove the build badge

2021-01-04 18:58 UTC, iambmelt approved these changes

2021-01-04 19:14 UTC, merged