Shadow for new Http Client
AzureAD/microsoft-authentication-library-for-android pull request #1279
Opened 2021-01-18 16:42 UTC by gitaumoses4

## What does this PR do?

Updates the shadows for HttpRequest to use the new HttpClient.

The update was done [here](https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/1161)

## Related discussion
https://github.com/AzureAD/microsoft-authentication-library-for-android/pull/1270#issuecomment-756494761

2021-01-18 17:36 UTC, shahzaibj commented
@gitaumoses4 Tests are failing...I believe this is because submodule is out of date. You would need to update the common submodule to point to the latest code on `dev` so that the HttpClient code from common gets used in these tests.

2021-01-18 17:38 UTC, shahzaibj requested changes
Tests are failing. Need to update common submodule.

2021-01-18 18:01 UTC, shahzaibj requested changes
The tests still seem to be failing. Were they passing on you local machine? 

The reason for these failures now I believe to be an issue with the shadow itself. Since what you are shadowing now is no longer a static method but rather an instance method, I believe you probably need to put the `@Implementation` annotation on the shadowed methods. See this for reference: http://robolectric.org/extending/#:~:text=Shadow%20objects%20implement%20methods%20that,the%20Android%20object%20is%20invoked.

2021-01-25 14:55 UTC, gitaumoses4 commented
Hi @shahzaibj , The tests are now passing locally. Only the `SingleAccountOverloadsMockedTest` is failing. Still trying to figure out why.

2021-01-29 17:43 UTC, shahzaibj commented on msal/src/test/java/com/microsoft/identity/client/e2e/tests/mocked/SingleAccountOverloadsMockedTest.java
> +        MockHttpResponse.setHttpResponse(MockServerResponse.getMockCloudDiscoveryResponse(), HttpClient.HttpMethod.GET);
should we specific about url here?

2021-01-29 17:44 UTC, shahzaibj commented on msal/src/test/java/com/microsoft/identity/client/e2e/shadows/ShadowHttpClient.java
> +public class ShadowHttpClient {
add javadoc

2021-02-01 10:42 UTC, gitaumoses4 commented on msal/src/test/java/com/microsoft/identity/client/e2e/tests/mocked/SingleAccountOverloadsMockedTest.java
> +        MockHttpResponse.setHttpResponse(MockServerResponse.getMockCloudDiscoveryResponse(), HttpClient.HttpMethod.GET);
Yes, I have added the regex.

2021-02-03 17:30 UTC, shahzaibj commented on msal/src/test/java/com/microsoft/identity/client/e2e/tests/mocked/SingleAccountOverloadsMockedTest.java
> +        ShadowHttpClient.class, ShadowOpenIdProviderConfigurationClient.class
```suggestion
        ShadowHttpClient.class, 
        ShadowOpenIdProviderConfigurationClient.class
```

2021-02-03 17:31 UTC, shahzaibj approved these changes

2021-02-08 19:27 UTC, tanmaymanolkar1 approved these changes

2021-02-09 04:27 UTC, merged