API Changes, deprecating all methods not using TokenParameters. WIP
AzureAD/microsoft-authentication-library-for-android pull request #1595
Opened 2022-02-16 06:51 UTC by fadidurah

Hey folks, early stages of the api-changes to deprecate all methods not using TokenParameters. Feel free to look over changes as they come in and give feedback.

2022-02-22 23:52 UTC, fadidurah commented
Please take a look at this common PR: https://github.com/AzureAD/microsoft-authentication-library-common-for-android/pull/1682

Above PR is a dependency for this one, need to add fields to PublicApiId,java

2022-03-08 17:24 UTC, shoatman approved these changes
Fadi - Please build a new version of MSAL with your changes and try and upgrade the existing sample app to ensure that we haven't missed/broken anything with this fix.  We may want to get Teams to try and create a build with these changes as well.... in fact I think we should plan on it.

2022-03-08 17:24 UTC, shoatman commented on msal/src/main/java/com/microsoft/identity/client/IPublicClientApplication.java
> +     * @deprecated  This method is now deprecated. The library is moving towards standardizing the use of TokenParameter subclasses as the
I think we should leave the existing javadoc.

2022-03-09 23:03 UTC, fadidurah commented on msal/src/main/java/com/microsoft/identity/client/IPublicClientApplication.java
> +     * @deprecated  This method is now deprecated. The library is moving towards standardizing the use of TokenParameter subclasses as the
Yes, think i missed this one when i restored the other javadocs, i'll put this one back and check for other ones i missed.

2022-03-12 02:15 UTC, fadidurah commented on msal/src/main/java/com/microsoft/identity/client/IPublicClientApplication.java
> +     * @deprecated  This method is now deprecated. The library is moving towards standardizing the use of TokenParameter subclasses as the
Actually, this is already fixed, I think you were viewing a version that didn't have all commits applied.

2022-03-14 20:29 UTC, iamgusain requested changes
added some minor comments

2022-03-14 20:29 UTC, iamgusain commented on msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java
> +    public void acquireTokenWithDeviceCode(@NonNull String[] scopes, @NonNull final DeviceCodeFlowCallback callback) {
Do we need to add this method? This is marked as @Deprecated

2022-03-14 20:29 UTC, iamgusain commented on msal/src/main/java/com/microsoft/identity/client/SignInParameters.java
> +package com.microsoft.identity.client;
Please add "Copyright text"  at the top.

2022-03-14 20:29 UTC, iamgusain commented on msal/src/main/java/com/microsoft/identity/client/SignInParameters.java
> + * Encapsulates the parameters for calling signIn() in SingleAccountPublicClientApplication.
Nit: can we add a link here to SingleAccountPublicClientApplication and signIn()?

2022-03-14 20:29 UTC, iamgusain commented on msal/src/main/java/com/microsoft/identity/client/SignInParameters.java
> + * Scopes    -  The non-null array of scopes to be consented to during sign in.
nit: List

2022-03-14 20:29 UTC, iamgusain commented on msal/src/main/java/com/microsoft/identity/client/SignInParameters.java
> + *              If no argument is supplied the default behavior will be used.
nit: lets add the value for default behavior

2022-03-14 20:29 UTC, iamgusain commented on msal/src/main/java/com/microsoft/identity/client/PublicClientApplication.java
> +    public void acquireTokenWithDeviceCode(@NonNull String[] scopes, @NonNull final DeviceCodeFlowCallback callback) {
Nvm, got confused with the diff shown here..

2022-03-15 19:12 UTC, fadidurah reviewed
Addressed Amit's Comments

2022-03-15 19:28 UTC, iamgusain approved these changes

2022-03-15 19:30 UTC, iamgusain commented
@fadidurah can you also add an entry in chagelog file. and mark it as [Major]

2022-03-15 19:31 UTC, iamgusain commented
> @fadidurah can you also add an entry in changelog file. and mark it as [Major]

Also please add a link to your "api change design document PR" in the description for this PR

2022-03-15 21:33 UTC, iamgusain approved these changes

2022-03-22 22:23 UTC, merged

2022-07-28 23:59 UTC, negoe commented
> This is the first in a two-step plan, where the deprecation is included in the next major release, and followed by deletion of these deprecating methods in the following release.

@fadidurah Can we please clarify in the sentence that deletion will be in next 'major' version release instead of following release?