Native auth extensibility
AzureAD/microsoft-authentication-library-for-android pull request #1968
Opened 2023-12-04 17:26 UTC by Yuki-YuXin

Include those commits
![image](https://github.com/AzureAD/microsoft-authentication-library-for-android/assets/111055878/3b0eccec-b362-478c-b7c5-2b05e0f7cd6a)

2023-12-11 12:13 UTC, SammyO commented on msal/src/main/java/com/microsoft/identity/client/statemachine/states/SignUpStates.kt
> -/**
Why were these comments removed?

2023-12-11 12:14 UTC, SammyO commented on msal/src/main/java/com/microsoft/identity/client/statemachine/states/SignUpStates.kt
> - * Native Auth uses a state machine to denote state and transitions for a user.
Same here

2023-12-11 12:14 UTC, SammyO commented on msal/src/main/java/com/microsoft/identity/client/statemachine/states/SignUpStates.kt
> - * Native Auth uses a state machine to denote state and transitions for a user.
And here

2023-12-11 12:14 UTC, SammyO commented on msal/src/main/java/com/microsoft/identity/client/statemachine/states/SignUpStates.kt
> - * Native Auth uses a state machine to denote state and transitions for a user.
And herre

2023-12-13 16:44 UTC, SaurabhMSFT requested changes

2023-12-13 16:44 UTC, SaurabhMSFT commented on msal/src/main/java/com/microsoft/identity/client/statemachine/results/SignUpResult.kt
> + * TODO add documentation & links to learn.microsoft.com
can you remove this todo?

2023-12-13 16:44 UTC, SaurabhMSFT commented on msal/src/main/java/com/microsoft/identity/client/INativeAuthPublicClientApplication.kt
> -    /**
Can you restore deleted comments from this file?

2023-12-13 16:44 UTC, SaurabhMSFT commented on msal/src/main/java/com/microsoft/identity/client/NativeAuthPublicClientApplication.kt
> +                is SignInCommandResult.Complete -> {
We can merge the clauses for `Complete`, `InvalidCredentials` and `UnknownError` into `else` block. Or at least  `Complete`, `InvalidCredentials`  can be merged into a single else block.

2023-12-13 16:44 UTC, SaurabhMSFT commented on msal/src/main/java/com/microsoft/identity/client/statemachine/results/ResetPasswordResult.kt
> + * TODO add documentation & links to learn.microsoft.com
We should remove this TODO as the link to documentation has been added below.

2023-12-13 16:44 UTC, SaurabhMSFT commented on msal/src/main/java/com/microsoft/identity/client/statemachine/states/BaseStates.kt
> +abstract class BaseState(internal open val flowToken: String?)
New line should be added at the end.

2023-12-13 16:44 UTC, SaurabhMSFT commented on msal/src/main/java/com/microsoft/identity/client/statemachine/states/ResetPasswordStates.kt
> -/**
Can you restore this comment

2023-12-13 16:44 UTC, SaurabhMSFT commented on msal/src/main/java/com/microsoft/identity/client/statemachine/states/ResetPasswordStates.kt
> -     * ResendCodeCallback receives the result for submit code for Reset Password for Native Auth
Can you restore this comment

2023-12-13 16:44 UTC, SaurabhMSFT commented on msal/src/main/java/com/microsoft/identity/client/statemachine/states/ResetPasswordStates.kt
> - * Native Auth uses a state machine to denote state and transitions for a user.
Can you restore this comment?

2023-12-13 16:44 UTC, SaurabhMSFT commented on msal/src/test/java/com/microsoft/identity/nativeauth/NativeAuthPublicClientApplicationJavaTest.java
> +        assertTrue(result instanceof SignInUsingPasswordError);
We should avoid using `assertTrue` where we are no comparing a boolean object. If `assertTrue` fails in this case then we won't know from the test run about the actual class  of `result`. Below shows an example using `assertThat`

https://stackoverflow.com/questions/12404650/assert-an-object-is-a-specific-type

2023-12-13 16:50 UTC, closed without merging