Update comments for Native Auth classes
AzureAD/microsoft-authentication-library-for-android pull request #1976
Opened 2023-12-13 16:10 UTC by SaurabhMSFT

2023-12-13 16:12 UTC, SammyO approved these changes

2023-12-13 16:53 UTC, SammyO requested changes

2023-12-13 16:53 UTC, SammyO commented on msal/src/main/java/com/microsoft/identity/nativeauth/NativeAuthPublicClientApplication.kt
> +            verifyNoUserIsSignedIn()
Test

2023-12-13 16:54 UTC, SammyO approved these changes

2023-12-14 14:44 UTC, Yuki-YuXin approved these changes

2023-12-15 09:07 UTC, merged